version: '3.3'
services:
  postgres:
    image: postgres:alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: getchapull
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  spring:
    build:
      context: ../getchapull-spring-backend/
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8081:8080"

  vue:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      - spring
